version: '0.1'
 
services:
  springboot-app:
    image: task1:1.0.1 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task1_backend
    depends_on:
      - mysql
    ports:
      - "8080:8081"
    networks:
      - task1_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://task1_db:3306/task1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8082:8082"
    depends_on:
      - service-discovery

  
  mysql:
    image: mysql:latest
    container_name: task1_container
    ports:
      - "3304:3306"
    networks:
      -  task1_network
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE: task1
    volumes:
      - task1_vol:/var/lib/mysql
networks:
  task1_network:
  
volumes:
  task1_vol: